Repository elastic/opbeans-python, pull requests merged in 2019-11, with the labels that each got.

#38 [jjbb] check_paths_for_matches.py not required anymore
  .ci/bin/check_paths_for_matches.py
Labels: automation, ci

#39 ci(jenkins): Update Jenkins badge
  README.md
Labels: automation, ci

#40 feat: enable environment settings on Docker compose files
  .editorconfig
  docker-compose-elastic-cloud.yml
  docker-compose.yml
Labels: automation, enhancement

#41 ci(jenkins): enable release process
  .ci/bump-version.sh
  .dockerignore
  .gitignore
  Makefile
Labels: automation
